add comments

diff --git a/.github/workflows/validate-airflow-dags.yml b/.github/workflows/validate-airflow-dags.yml
--- a/.github/workflows/validate-airflow-dags.yml
+++ b/.github/workflows/validate-airflow-dags.yml
@@ -121,7 +121,15 @@ jobs:
             echo "Validating DAG: $dag_file"
 
             # Validate the DAG file
-            python -c "from airflow.models import DagBag;dag_bag = DagBag(dag_folder=None,include_examples = False); dag_bag.process_file('$dag_file'); print(dag_bag.import_errors); assert not dag_bag.import_errors" || exit 1
+            python -c "from airflow.models import DagBag;dag_bag = DagBag(dag_folder='None',include_examples = False); dag_bag.process_file('$dag_file'); print(dag_bag.import_errors); assert not dag_bag.import_errors" || exit 1
 
             echo "DAG $dag_file is valid."
           done
+
+# Step 6 Breakdown
+# The last step in the workflow validates the new or modified DAG files.
+# The script loops through each DAG file and validates it using the `DagBag` class from the Airflow library.
+# The `DagBag` class is used to process a DAG file and check for any import errors.
+# dag_bag is initialized with an empty path so that only 1 dag file is processed at a time.
+# If there are any import errors, the script exits with a non-zero status code, indicating that the DAG file is invalid.
+# If all DAG files are valid, the script prints a success message for each DAG file.
